/*
 * This file was generated by the Gradle 'init' task.
 */

version = "2.0.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

plugins {
    `java-library`
}

tasks.jar {
    manifest {
        attributes(mapOf("Bundle-ManifestVersion" to "2",
                         "Bundle-Name" to "Model Library",
                         "Bundle-SymbolicName" to project.name,
                         "Bundle-Version" to project.version,
                         "Bundle-Vendor" to "UMMISCO"))
    }
}

sourceSets {
    main {
        resources {
            setSrcDirs(listOf("src"))
        }
    }
}

